Make Scene response struct compatible with Scenes + SceneItems API
dnaka91/obws pull request #39
Opened 2024-06-01 06:44 UTC by etymonym

The `GetSceneList` request for `obs-websocket` [includes a UUID for each scene in the list](https://github.com/obsproject/obs-websocket/blob/master/src/utils/Obs_ArrayHelper.cpp#L99), but the [response struct `Scene`](https://docs.rs/obws/latest/obws/responses/scenes/struct.Scene.html) used in the `scenes` field of the return type for the [analogous API function](https://docs.rs/obws/latest/obws/client/struct.Scenes.html#method.list) does not de-serialize it. 

As a result, most of the API made available through [`Scenes`](https://docs.rs/obws/latest/obws/client/struct.Scenes.html) and [`SceneItems`](https://docs.rs/obws/latest/obws/client/struct.SceneItems.html) is rendered inaccessible for any scene that isn't currently the Preview or Program scene ( each of which are made available as `SceneId` and so are usable with said APIs ).

This addition adds a field for the `sceneUuid` to be de-serialized to, in addition to adding a `From<Scene>` implementation for `SceneId`  that simply drops the `index` field of `Scene`. This makes it so that all scenes can be used with the `Scenes` and `SceneItems` APIs after calling `.into()`

Please let me know if I've missed anything and I'd be more than happy to make corrections.

2024-06-02 12:07 UTC, dnaka91 requested changes
Thank you for the PR!

Basically looks good but I'd prefer to embed the `SceneId` directly in the struct to stay consistent with the rest of the code base.

Meaning to replace the current field with `pub id: SceneId` instead of adding the uuid field.

2024-06-03 21:58 UTC, dnaka91 commented
I fixed this in the latest commit on `main`. Probably will do a new breaking release as beta or rc instead of a full release as there might be a few more oversights here and there.

2024-06-03 21:58 UTC, closed without merging

2024-06-04 09:35 UTC, etymonym commented
Ok! Thought there might be something like that as I wasn't sure how you'd want to apply the change and felt like this was the most minimal way to model a solution.

Thank you for the quick turn around! I'll keep my eye out for anything else like this when I return to my project in a few days and submit any issues / relevant PRs that crop up.

2024-06-04 11:33 UTC, dnaka91 commented
Thanks, that'd be great. I myself only actively use a fraction of the whole API and am happy for anyone giving feedback on other parts of the API.